name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy App
        run: pnpm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Publish secrets to Cloudflare Worker
        run: |
          cd apps/admin
          echo "${{ secrets.SUPABASE_SECRET_KEY }}" | npx wrangler secret put --env production SUPABASE_SECRET_KEY
          echo "${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}" | npx wrangler secret put --env production NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
          echo "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" | npx wrangler secret put --env production NEXT_PUBLIC_SUPABASE_URL
          echo "${{ secrets.SUPABASE_DB_PASSWORD }}" | npx wrangler secret put --env production SUPABASE_DB_PASSWORD
          echo "${{ secrets.SUPABASE_PROJECT_ID }}" | npx wrangler secret put --env production SUPABASE_PROJECT_ID
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
