name: Deploy Cloudflare Worker

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Publish secrets to Cloudflare Worker
        env: 
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd apps/admin
          echo "${{ secrets.SUPABASE_SECRET_KEY }}" | npx wrangler secret put --env production SUPABASE_SECRET_KEY
          echo "${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" | npx wrangler secret put --env production SUPABASE_PUBLISHABLE_KEY
          echo "${{ secrets.SUPABASE_DB_PASSWORD }}" | npx wrangler secret put --env production SUPABASE_DB_PASSWORD
          echo "${{ secrets.SUPABASE_PROJECT_ID }}" | npx wrangler secret put --env production SUPABASE_PROJECT_ID

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          cd apps/admin
          wrangler deploy --env production
