name: Deploy to Cloudflare Workers

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Provision Resources"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if the provision workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        app: ["backend", "landing", "admin"]
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Database Migrations
        env:
          POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
        run: |
          cd packages/db
          pnpm run migrate

      - name: Deploy Cloudflare Workers
        env:
          # These repository variables are set by the provision workflow
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.SUPABASE_PUBLIC_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ vars.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_ENVIRONMENT: production
          # Set sentry DSN for each app
          NEXT_PUBLIC_SENTRY_DSN: ${{ vars[format('SENTRY_DSN_{0}_PUBLIC', matrix.app)] }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_BACKEND_URL: https://uzairname.org
        run: |
          cd apps/${{ matrix.app }}
          pnpm run deploy:prod

      - name: Set Cloudflare Worker Secrets
        env:
          SENTRY_DSN_PUBLIC: ${{ matrix.app == 'backend' && vars.SENTRY_DSN_BACKEND_PUBLIC || matrix.app == 'landing' && vars.SENTRY_DSN_LANDING_PUBLIC || vars.SENTRY_DSN_ADMIN_PUBLIC }}
        run: |
          WORKER_NAME="template-${{ matrix.app }}"
          echo "Setting secrets for worker: $WORKER_NAME"

          echo "${{ vars.SUPABASE_PUBLIC_URL }}" | npx wrangler secret put SUPABASE_PUBLIC_URL --name $WORKER_NAME
          echo "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" | npx wrangler secret put SUPABASE_SERVICE_ROLE_KEY --name $WORKER_NAME
          echo "${{ secrets.SUPABASE_DB_PASSWORD }}" | npx wrangler secret put SUPABASE_DB_PASSWORD --name $WORKER_NAME
          echo "${{ secrets.POSTGRES_URI }}" | npx wrangler secret put POSTGRES_URI --name $WORKER_NAME
          echo "${{ secrets.APP_KEY }}" | npx wrangler secret put APP_KEY --name $WORKER_NAME
          echo "$SENTRY_DSN_PUBLIC" | npx wrangler secret put SENTRY_DSN_PUBLIC --name $WORKER_NAME
          echo "incremental-cache-template-${{ matrix.app }}-production" | npx wrangler secret put NEXT_INC_CACHE_R2_PREFIX --name $WORKER_NAME
